### ISSUE TITLE
求解获取的返回数据怎么解码

### ISSUE THREAD

**Issue by DirectLinkSs** [SeeFlowerX/bilibili-grpc-api#1]
运行 run.py 输出的内容。请问大佬怎么解码呢。
![image](https://user-images.githubusercontent.com/17827407/100746005-166dfb80-341b-11eb-8d27-7a248af5e23e.png)

**Comment by SeeFlowerX** [comment]
> 返回数据proto文件构成复杂，有需要可以参考[上面的文章](https://blog.seeflower.dev/explore-bilibili-video-grpc-request/)**自行编写proto文件**。

编写proto文件后，生成对应的py文件，通过[ParseFromString](https://github.com/SeeFlowerX/bilibili-grpc-api/blob/a99f156afd747df9419b70ecd95436bf5e853e2e/service/subtitle.py#L45)就可以解码了，`MessageToDict`可以帮助格式化。

**Comment by DirectLinkSs** [comment]
看不懂逆向，折腾了半天。
大佬NB，全网就这一篇文章。

**Comment by DirectLinkSs** [comment]
> 运行 run.py 输出的内容。请问大佬怎么解码呢。
> ![image](https://user-images.githubusercontent.com/17827407/100746005-166dfb80-341b-11eb-8d27-7a248af5e23e.png)
